runtime: php82
entrypoint: serve index.php

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

env_variables:
  # Replace user, password, database, and instance_connection_name with the
  # values obtained from your Cloud SQL instance.
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: SuperServer12
  CLOUDSQL_DSN: mysql:unix_socket=/cloudsql/lions-king:northamerica-northeast1:lions-king;dbname=gym_database

beta_settings:
  cloud_sql_instances: lions-king:northamerica-northeast1:lions-king
